dsn: ${TBLS_DATABASE_URL}?sslmode=disable

name: cbd
docPath: docs/db
exclude:
  - _prisma_migrations

format:
  adjust: true

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created_at
      - updated_at
  requireColumns:
    enabled: true
    columns:
      - name: created_at
      - name: updated_at

comments:
  - table: public.beans
    tableComment: Whole beans
    columnComments:
      id: Whole bean ID
      name: Whole bean name
      description: Whole bean description
      roast_level_id: Roast level ID
      origin_id: Origin ID
      processing_method_id: Processing method ID

  - table: public.origins
    tableComment: Coffee origins
    columnComments:
      id: Coffee origin ID
      name: Coffee origin name
      description: Coffee origin description
      longitude: Coffee origin longitude
      latitude: Coffee origin latitude

  - table: public.roast_levels
    tableComment: Coffee roast levels
    columnComments:
      id: Coffee roast level ID
      name: Coffee roast level name
      description: Coffee roast level description

  - table: public.processing_methods
    tableComment: Coffee processing methods
    columnComments:
      id: Coffee processing method ID
      name: Coffee processing method name
      description: Coffee processing method description

  - table: public.flavor_profiles
    tableComment: Coffee flavor profiles
    columnComments:
      id: Coffee flavor profile ID
      value: Coffee flavor profile value
      label: Coffee flavor profile label
      description: Coffee flavor profile description

  - table: public.bean_flavor_profiles
    tableComment: Bean flavor profiles relationship
    columnComments:
      bean_id: Bean ID
      flavor_profile_id: Flavor profile ID

  - table: public.tastings
    tableComment: Coffee tasting
    columnComments:
      id: Coffee tasting ID
      name: Coffee tasting name
      description: Coffee tasting description
      acidity: Coffee tasting acidity
      richness: Coffee tasting richness
      conducted_at: Coffee tasting conducted at

  - table: public.bean_tastings
    tableComment: Bean tastings relationship
    columnComments:
      bean_id: Bean ID
      tasting_id: Tasting ID

  - table: public.packs
    tableComment: Coffee packs
    columnComments:
      id: Coffee pack ID
      name: Coffee pack name
      description: Coffee pack description

  - table: public.beans_packs
    tableComment: Beans packs relationship
    columnComments:
      bean_id: Bean ID
      pack_id: Pack ID

  - table: flavor_profile_trees
    tableComment: Coffee flavor profile trees
    columnComments:
      id: Coffee flavor profile tree ID
      parent_id: Coffee flavor profile tree parent ID
      child_id: Coffee flavor profile tree child ID

  - table: public.shops
    tableComment: Coffee shops
    columnComments:
      id: Coffee shop ID
      name: Coffee shop name

  - table: public.shop_locations
    tableComment: Coffee shop locations
    columnComments:
      id: Coffee shop location ID
      shop_id: Coffee shop ID
      longitude: Coffee shop location longitude
      latitude: Coffee shop location latitude
      postal_code: Coffee shop location postal code
      prefecture: Coffee shop location prefecture
      city: Coffee shop location city
      address: Coffee shop location address
  
  - table: public.pack_purchases
    tableComment: Coffee pack purchases
    columnComments:
      id: Coffee pack purchase ID
      pack_id: Coffee pack ID
      shop_id: Coffee shop ID
      price: Coffee pack purchase price
      capacity: Coffee pack purchase capacity
      purchased_at: Coffee pack purchased at